kind: PersistentVolume
apiVersion: v1
metadata:
  name: media-pv
  labels:
    type: local
spec:
  storageClassName: media-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./web/media