apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pv-claim
  labels:
    type: local
spec:
  storageClassName: media-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: media-pv