apiVersion: v1
kind: Service
metadata:
  name: kubernetes-django-service
spec:
  selector:
    app: django-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort