apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pv-claim
  labels:
    type: local
spec:
  storageClassName: static-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: static-pv