version: '3.4'

services:
  django:
    image: web
    user: "web:web"
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - static_volume:/home/web/static
      - media_volume:/home/web/media
volumes:
  static_volume:
  media_volume: