services:
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  db:
    image: postgres:alpine
    labels:
      kompose.volume.type: persistentVolumeClaim
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - .env
    ports:
      - "5432"
  redis:
    image: redis:alpine
    ports:
      - "6379"
  web:
    labels:
      kompose.image-pull-policy: "IfNotPresent"
      kompose.volume.type: persistentVolumeClaim
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dockerbird_web:latest
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web:./web
      - static_volume:/home/web/static
      - media_volume:/home/web/media
    env_file:
      - .env
    depends_on:
      - cache
      - redis
      - db
    ports:
      - "8000"
  celery:
    labels:
      kompose.image-pull-policy: "IfNotPresent"
      kompose.volume.type: persistentVolumeClaim
    image: dockerbird_web:latest
    command: celery -A web worker -l info
    volumes:
      - ./web:./web
      - static_volume:/home/web/static
      - media_volume:/home/web/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web
    ports:
      - "8000"
  celery-beat:
    labels:
      kompose.image-pull-policy: "IfNotPresent"
      kompose.volume.type: persistentVolumeClaim
    image: dockerbird_web:latest
    command: celery -A web beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./web:./web
      - static_volume:/home/web/static
      - media_volume:/home/web/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web
    ports:
      - "8000"
  nginx:
    labels:
      kompose.volume.type: persistentVolumeClaim
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/web/static
      - media_volume:/home/web/media
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  postgres_data: {}
  static_volume: {}
  media_volume: {}