kind: PersistentVolume
apiVersion: v1
metadata:
  name: static-pv
  labels:
    type: local
    app: dockerbird
spec:
  storageClassName: static-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/web/static
